[vehicle_1]
type = "car"
length = 4.5
width = 2.0
desired_speed = 15.0
jam_distance = 1.0
desired_time_gap = 1.0
max_acceleration = 2.0
desired_deceleration = 3.0
delta = 4
safe_brake = 4
politeness = 0.5
acc_threshold = 0.3
is_lc_allowed = true
lon_pos = -100.0
lat_pos = 3.5
heading = 0.0
speed = 15.0
lane = 1

[vehicle_2]
type = "car"
length = 4.5
width = 2.0
desired_speed = 15.0
jam_distance = 2.0
desired_time_gap = 1.0
max_acceleration = 2.0
desired_deceleration = 3.0
delta = 4
safe_brake = 4
politeness = 0.0
acc_threshold = 0.3
is_lc_allowed = true
lon_pos = -10.0
lat_pos = 0.0
heading = 0.0
speed = 15.0
lane = 0

[vehicle_3]
type = "car"
length = 4.5
width = 2.0
desired_speed = 10.0
jam_distance = 2.0
desired_time_gap = 1.0
max_acceleration = 2.0
desired_deceleration = 3.0
delta = 4
safe_brake = 4
politeness = 0.5
acc_threshold = 0.3
is_lc_allowed = false
lon_pos = -20.0
lat_pos = 0.0
heading = 0.0
speed = 10.0
lane = 0

[vehicle_4]
type = "car"
length = 4.5
width = 2.0
desired_speed = 10.0
jam_distance = 2.0
desired_time_gap = 1.0
max_acceleration = 2.0
desired_deceleration = 3.0
delta = 4
safe_brake = 4
politeness = 0.5
acc_threshold = 0.3
is_lc_allowed = false
lon_pos = -0.0
lat_pos = 3.5
heading = 0.0
speed = 10.0
lane = 1